name: $(date:yyyy.MM.dd)$(rev:.r)
trigger:
  batch: true
  branches:
    include:
      - master

stages:
  - stage: Build
    displayName: Build function app
    jobs:
      - job: Build
        displayName: Build app
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            clean: true

          - task: UseDotNet@2
            displayName: 'Use .Net Core sdk 6.x'
            inputs:
              version: 6.0.x

          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet test'
            inputs:
              command: 'test'
              projects: '**/*.csproj'
              arguments: '--no-restore --configuration Release --framework net6.0'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet publish'
            inputs:
              command: 'publish'
              projects: 'AzureFunctionApp/AzureFunction.App/AzureFunction.App.csproj'
              publishWebProjects: false
              arguments: '--no-restore --no-build --configuration Release --output $(build.artifactstagingdirectory) --framework net6.0'
              
          - template: azure-resource-group-deployment.yml
            parameters:
              displayName: Check resource template
              azureSubscription: '$(azureResourceManagerConnection)'
              deploymentName: 'check'
              resourceGroupName: '$(resourceGroupName)'
              location: '$(location)'
              templateFile: 'AzureFunctionApp/AzureFunction.Infrastructure/Templates/resourceGroup.iac.bicep'
              whatIf: true

          - task: CopyFiles@2
            displayName: 'Copy resource template to artifacts'
            inputs:
              SourceFolder: AzureFunctionApp/AzureFunction.Infrastructure/Templates 
              Contents: 'resourceGroup.iac.bicep'
              TargetFolder: '$(build.artifactstagingdirectory)'

          - publish: $(build.artifactstagingdirectory)
            displayName: 'Publish Artifact: drop'
            artifact: drop
            condition: succeededOrFailed()
  
  - stage: Deploy
    displayName: Deploy function app
    condition: succeeded()
    jobs:
      - deployment: Deploy
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                  
                - template: azure-resource-group-deployment.yml
                  parameters:
                    displayName: Deploy resource group infrastructure
                    azureSubscription: '$(azureResourceManagerConnection)'
                    deploymentName: 'continuous-deployment'
                    resourceGroupName: '$(resourceGroupName)'
                    location: '$(location)'
                    templateFile: '$(Pipeline.Workspace)/drop/resourceGroup.iac.bicep'

                - task: AzureFunctionApp@1
                  displayName: Deploy function app
                  inputs:
                    azureSubscription: $(azureResourceManagerConnection)
                    appType: 'functionAppLinux'
                    appName: $(appName)
                    package: '$(Pipeline.Workspace)/drop/AzureFunction.App.zip'
                    appSettings: '-FUNCTIONS_EXTENSION_VERSION ~4'
                    runtimeStack: 'DOCKER|mcr.microsoft.com/azure-functions/dotnet:4-appservice'